### ISSUE TITLE
Join CloudFormation lines with \n

### ISSUE THREAD

**Issue by zaus** [sopel/stackformation#2]
Can't you join with `"\n"` rather than "" and appending `\n` to every line?

Specifically, at https://github.com/sopel/stackformation/blob/master/templates/newrelic-cloudwatch-plugin-spot.template#L200

**Comment by sopel** [comment]
@zaus - agreed, that might make more sense there, thanks for pointing it out (a few entries do not currently use `\n` though, which would need to be accounted for in case). I meanwhile consider this approach for embedding scripts in CloudFormation templates a bit old fashioned anyway, these days I usually constrain the `UserData` section to a fragment referencing an external script rather than doing it inline, which has the benefit that your business logic can be tested and source controlled as usual.
- :information_source: Also, as hinted on in the [README](https://github.com/sopel/stackformation/blob/master/README.md), this project has never left the _Very early stages, not much to see/use_ stage and will be retired accordingly, sorry for not tackling this earlier (will be handled via #3).

**Comment by sopel** [comment]
Closed as _Won't Fix_ due to project being retired (see #3).
